#!/usr/bin/env python
import sys
from StocksBar.server import bar_server
from StocksBar.product import product

if __name__ == "__main__":
    s = bar_server()
    s.add_product(product('Beer', 8, 13, 10))
    s.add_product(product('Moscow Mule', 15, 23, 17))
    s.add_product(product('Blood Mary', 25, 30, 26))
    s.add_product(product('Martini', 15, 23, 17))
    s.add_product(product('French Fries', 10, 23, 17))
    s.add_product(product('French Fries', 10, 20, 17))
    s.add_product(product('Hamburguer', 15, 30, 25))
    s.add_product(product('Pizza', 30, 40, 31))
    s.add_product(product('Water', 1, 4, 2))
    s.add_product(product('Coca', 2, 5, 3))
    s.add_product(product('Guarana', 2, 5, 3))
    s.add_product(product('Sprite', 2, 5, 3))
    s.add_product(product('Fanta', 2, 5, 3))
    s.run()