#!/usr/bin/env python
import sys
from StocksBar.server import bar_server
from StocksBar.product import product

if __name__ == "__main__":
    s = bar_server()
    s.add_product(product('Beer', 8, 13, 10))
    s.add_product(product('Drink', 15, 23, 17))
    s.run()